Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0

/home/Insvenv/local/lib/python2.7/site-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2017-10-17 14:52:42,303: WARNING/MainProcess] /home/Insvenv/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-10-17 14:52:42,338: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2017-10-17 14:52:42,344: INFO/MainProcess] mingle: searching for neighbors
[2017-10-17 14:52:43,348: INFO/MainProcess] mingle: all alone
[2017-10-17 14:52:43,356: WARNING/MainProcess] /home/Insvenv/local/lib/python2.7/site-packages/djcelery/loaders.py:130: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warn('Using settings.DEBUG leads to a memory leak, never '
[2017-10-17 14:52:43,356: WARNING/MainProcess] celery@ubuntu ready.
[2017-10-17 14:53:32,810: INFO/MainProcess] Received task: ins.task.send_email_inner[f9b24cee-aae7-46f5-a4e4-7c2082e4f9c9]
[2017-10-17 14:53:33,377: INFO/MainProcess] Task ins.task.send_email_inner[f9b24cee-aae7-46f5-a4e4-7c2082e4f9c9] succeeded in 0.565782902995s: None
[2017-10-17 14:53:58,988: INFO/MainProcess] Received task: ins.task.send_email_inner[5a15289b-628e-4338-83e4-4766b80c6516]
[2017-10-17 14:53:59,449: INFO/MainProcess] Task ins.task.send_email_inner[5a15289b-628e-4338-83e4-4766b80c6516] succeeded in 0.460475747008s: None
[2017-10-17 14:57:32,352: INFO/MainProcess] Received task: ins.task.send_email_inner[5105953e-698f-4d47-986a-d919f93cb090]
[2017-10-17 14:57:32,849: INFO/MainProcess] Task ins.task.send_email_inner[5105953e-698f-4d47-986a-d919f93cb090] succeeded in 0.495856624097s: None
[2017-10-17 15:02:26,047: INFO/MainProcess] Received task: ins.task.send_email_inner[8b854df0-3e08-4d2b-b4df-4350cbfec510]
[2017-10-17 15:02:26,629: INFO/MainProcess] Task ins.task.send_email_inner[8b854df0-3e08-4d2b-b4df-4350cbfec510] succeeded in 0.581330444897s: None
[2017-10-17 15:03:31,715: INFO/MainProcess] Received task: ins.task.send_email_inner[6189ecb5-0d25-4ee0-aa31-d20800a4c054]
[2017-10-17 15:03:32,254: INFO/MainProcess] Task ins.task.send_email_inner[6189ecb5-0d25-4ee0-aa31-d20800a4c054] succeeded in 0.538242523093s: None
[2017-10-17 15:06:03,765: INFO/MainProcess] Received task: ins.task.send_email_inner[afa72afb-a81f-4a44-88d4-50e0238016fa]
[2017-10-17 15:06:04,314: INFO/MainProcess] Task ins.task.send_email_inner[afa72afb-a81f-4a44-88d4-50e0238016fa] succeeded in 0.548041553004s: None
[2017-10-17 15:07:28,558: INFO/MainProcess] Received task: ins.task.send_email_inner[76480eff-9c70-458a-8600-bd3bc3521057]
[2017-10-17 15:07:29,059: INFO/MainProcess] Task ins.task.send_email_inner[76480eff-9c70-458a-8600-bd3bc3521057] succeeded in 0.499675472034s: None
[2017-10-17 15:11:49,382: INFO/MainProcess] Received task: ins.task.send_email_inner[61ca3e2a-d0bd-4de9-8b6a-16c97414a0a1]
[2017-10-17 15:11:49,903: INFO/MainProcess] Task ins.task.send_email_inner[61ca3e2a-d0bd-4de9-8b6a-16c97414a0a1] succeeded in 0.520461640088s: None
[2017-10-17 15:15:03,808: INFO/MainProcess] Received task: ins.task.send_email_inner[01a76630-0726-4280-ba9d-7d25e6a90b6a]
[2017-10-17 15:15:04,374: INFO/MainProcess] Task ins.task.send_email_inner[01a76630-0726-4280-ba9d-7d25e6a90b6a] succeeded in 0.564817517996s: None
[2017-10-17 15:16:51,204: INFO/MainProcess] Received task: ins.task.send_email_inner[3a8407e4-694a-43c3-b1f5-0a1a74c82735]
[2017-10-17 15:16:51,750: INFO/MainProcess] Task ins.task.send_email_inner[3a8407e4-694a-43c3-b1f5-0a1a74c82735] succeeded in 0.545889916131s: None
[2017-10-17 15:21:34,069: INFO/MainProcess] Received task: ins.task.send_email_inner[c16bb69f-d0b7-49ed-9738-695cb07909b8]
[2017-10-17 15:21:34,732: INFO/MainProcess] Task ins.task.send_email_inner[c16bb69f-d0b7-49ed-9738-695cb07909b8] succeeded in 0.662719384069s: None
[2017-10-17 15:24:29,185: INFO/MainProcess] Received task: ins.task.send_email_inner[852531df-93a7-4a63-93c2-05a37ff85148]
[2017-10-17 15:24:29,666: INFO/MainProcess] Task ins.task.send_email_inner[852531df-93a7-4a63-93c2-05a37ff85148] succeeded in 0.47993710218s: None

worker: Warm shutdown (MainProcess)

Restarting celery worker (manage.py celery worker --loglevel=info)

worker: Cold shutdown (MainProcess)
 
 -------------- celery@ubuntu v3.1.25 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-4.4.0-96-generic-x86_64-with-Ubuntu-16.04-xenial
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x7fbd2c5801d0 (djcelery.loaders.DjangoLoader)
- ** ---------- .> transport:   redis://127.0.0.1:6379//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . ins.task.send_email_inner

/home/Insvenv/local/lib/python2.7/site-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2017-10-19 01:01:21,327: WARNING/MainProcess] /home/Insvenv/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-10-19 01:01:21,366: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 2.00 seconds...

[2017-10-19 01:01:23,369: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 4.00 seconds...

[2017-10-19 01:01:27,375: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 6.00 seconds...

/home/Insvenv/local/lib/python2.7/site-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2017-10-19 01:01:31,778: WARNING/MainProcess] /home/Insvenv/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-10-19 01:01:31,816: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 2.00 seconds...

[2017-10-19 01:01:33,819: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 4.00 seconds...

[2017-10-19 01:01:37,825: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 6.00 seconds...

[2017-10-19 01:01:43,832: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 8.00 seconds...

[2017-10-19 01:01:51,842: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 10.00 seconds...

[2017-10-19 01:02:01,854: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 12.00 seconds...

[2017-10-19 01:02:13,870: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 14.00 seconds...

[2017-10-19 01:02:27,887: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 16.00 seconds...

[2017-10-19 01:02:43,906: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: .
Trying again in 18.00 seconds...

